import Foundation

/// A houseplant species with default care information
struct PlantSpecies: Identifiable {
    let id = UUID()
    let name: String
    let defaultWateringDays: Int
    let emoji: String

    init(_ name: String, wateringDays: Int, emoji: String) {
        self.name = name
        self.defaultWateringDays = wateringDays
        self.emoji = emoji
    }
}

/// Static database of 1000+ plants organized alphabetically
enum PlantSpeciesDatabase {
    static let database: [PlantSpecies] = [
        // A
        PlantSpecies("Abutilon - Flowering Maple", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Acacia", wateringDays: 7, emoji: "🌳"),
        PlantSpecies("Acalypha - Chenille Plant", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Achillea - Yarrow", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Adiantum - Maidenhair Fern", wateringDays: 3, emoji: "🌿"),
        PlantSpecies("Adenium - Desert Rose", wateringDays: 10, emoji: "🌺"),
        PlantSpecies("Aeonium", wateringDays: 10, emoji: "🪴"),
        PlantSpecies("Aeschynanthus - Lipstick Plant", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("African Mask Plant (Alocasia)", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Agapanthus - Lily of the Nile", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Agave", wateringDays: 21, emoji: "🪴"),
        PlantSpecies("Ageratum", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Aglaonema - Chinese Evergreen", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Ajuga - Bugleweed", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Alocasia - Elephant Ear", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Alocasia Polly", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Alocasia Zebrina", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Aloe Vera", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Alpinia - Ginger Plant", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Alternanthera", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Amaranth", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Amaryllis", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Ananas - Pineapple Plant", wateringDays: 7, emoji: "🍍"),
        PlantSpecies("Anemone", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Angel Wing Begonia", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Anthurium", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Anthurium Clarinervium", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Aphelandra - Zebra Plant", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Aralia", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Araucaria - Norfolk Island Pine", wateringDays: 7, emoji: "🌲"),
        PlantSpecies("Areca Palm", wateringDays: 5, emoji: "🌴"),
        PlantSpecies("Arrowhead Plant", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Asparagus Fern", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Aspidistra - Cast Iron Plant", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Asplenium - Bird's Nest Fern", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Aster", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Astrophytum - Star Cactus", wateringDays: 21, emoji: "🌵"),
        PlantSpecies("Azalea", wateringDays: 5, emoji: "🌺"),

        // B
        PlantSpecies("Baby Rubber Plant", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Baby's Breath", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Bamboo (Indoor)", wateringDays: 5, emoji: "🎋"),
        PlantSpecies("Bamboo Palm", wateringDays: 5, emoji: "🌴"),
        PlantSpecies("Banana Plant", wateringDays: 5, emoji: "🍌"),
        PlantSpecies("Basil", wateringDays: 3, emoji: "🌿"),
        PlantSpecies("Bay Laurel", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Begonia", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Begonia Maculata - Polka Dot Begonia", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Begonia Rex", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Bird of Paradise", wateringDays: 10, emoji: "🌺"),
        PlantSpecies("Bird of Paradise - White", wateringDays: 10, emoji: "🌺"),
        PlantSpecies("Black-Eyed Susan", wateringDays: 5, emoji: "🌼"),
        PlantSpecies("Bleeding Heart", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Blue Star Fern", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Boston Fern", wateringDays: 3, emoji: "🌿"),
        PlantSpecies("Bottlebrush", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Bougainvillea", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Boxwood", wateringDays: 7, emoji: "🌳"),
        PlantSpecies("Bromeliaceae - Bromeliad", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Brunfelsia - Yesterday Today Tomorrow", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Bulbs - Amaryllis", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Bulbs - Crocus", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Bulbs - Hyacinth", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Bulbs - Muscari", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Bulbs - Narcissus", wateringDays: 5, emoji: "🌼"),
        PlantSpecies("Bulbs - Tulip", wateringDays: 5, emoji: "🌷"),
        PlantSpecies("Burro's Tail (Sedum Morganianum)", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Button Fern", wateringDays: 5, emoji: "🌿"),

        // C
        PlantSpecies("Cactus - Barrel", wateringDays: 21, emoji: "🌵"),
        PlantSpecies("Cactus - Bishop's Cap", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Cactus - Bunny Ears (Opuntia)", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Cactus - Christmas", wateringDays: 10, emoji: "🌵"),
        PlantSpecies("Cactus - Chin (Gymnocalycium)", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Cactus - Column (Cereus)", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Cactus - Dragon Fruit", wateringDays: 10, emoji: "🌵"),
        PlantSpecies("Cactus - Easter", wateringDays: 7, emoji: "🌵"),
        PlantSpecies("Cactus - Fairy Castle", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Cactus - Fishhook", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Cactus - Golden Barrel", wateringDays: 21, emoji: "🌵"),
        PlantSpecies("Cactus - Hedgehog", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Cactus - Lace (Mammillaria)", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Cactus - Moon", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Cactus - Old Lady", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Cactus - Old Man", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Cactus - Organ Pipe", wateringDays: 21, emoji: "🌵"),
        PlantSpecies("Cactus - Peanut", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Cactus - Pincushion", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Cactus - Prickly Pear (Opuntia)", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Cactus - Rat Tail", wateringDays: 10, emoji: "🌵"),
        PlantSpecies("Cactus - Saguaro", wateringDays: 28, emoji: "🌵"),
        PlantSpecies("Cactus - San Pedro", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Cactus - Star", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Cactus - Thanksgiving", wateringDays: 10, emoji: "🌵"),
        PlantSpecies("Cactus - Totem Pole", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Caladium", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Calathea", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Calathea Medallion", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Calathea Orbifolia", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Calathea Rattlesnake", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Calathea White Fusion", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Calendula", wateringDays: 5, emoji: "🌼"),
        PlantSpecies("Calibrachoa - Million Bells", wateringDays: 3, emoji: "🌺"),
        PlantSpecies("Camellia", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Campanula - Bellflower", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Canna Lily", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Cape Jasmine", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Carnation", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Carnivorous Plant", wateringDays: 3, emoji: "🪴"),
        PlantSpecies("Cast Iron Plant", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Celosia", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Ceropegia - String of Hearts", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Chinese Money Plant", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Chlorophytum - Spider Plant", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Christmas Cactus", wateringDays: 10, emoji: "🌵"),
        PlantSpecies("Chrysanthemum", wateringDays: 5, emoji: "🌼"),
        PlantSpecies("Cineraria", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Cissus - Grape Ivy", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Citrus Tree (Indoor)", wateringDays: 7, emoji: "🍋"),
        PlantSpecies("Clematis", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Clerodendrum - Bleeding Heart Vine", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Clivia", wateringDays: 10, emoji: "🌺"),
        PlantSpecies("Clusia - Autograph Plant", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Codiaeum - Croton", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Coffee Plant", wateringDays: 5, emoji: "☕"),
        PlantSpecies("Coleus", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Columnea - Goldfish Plant", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Coneflower - Echinacea", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Coral Bells - Heuchera", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Cordyline", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Coreopsis", wateringDays: 7, emoji: "🌼"),
        PlantSpecies("Cosmos", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Cotoneaster", wateringDays: 7, emoji: "🌳"),
        PlantSpecies("Crassula - Jade Plant", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Crossandra", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Croton", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Crown of Thorns (Euphorbia milii)", wateringDays: 10, emoji: "🌺"),
        PlantSpecies("Ctenanthe", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Cuphea", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Cyclamen", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Cymbidium Orchid", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Cypress (Indoor)", wateringDays: 7, emoji: "🌲"),

        // D
        PlantSpecies("Daffodil", wateringDays: 5, emoji: "🌼"),
        PlantSpecies("Dahlia", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Daisy - Shasta", wateringDays: 5, emoji: "🌼"),
        PlantSpecies("Datura - Angel's Trumpet", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Davallia - Rabbit's Foot Fern", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Daylily", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Delphinium", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Deutzia", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Dianthus - Sweet William", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Dieffenbachia", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Digitalis - Foxglove", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Dionaea - Venus Flytrap", wateringDays: 3, emoji: "🪴"),
        PlantSpecies("Dischidia", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Dracaena", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Dracaena - Dragon Tree", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Dracaena - Lucky Bamboo", wateringDays: 7, emoji: "🎋"),
        PlantSpecies("Dracaena Janet Craig", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Dracaena Lemon Lime", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Dracaena Warneckii", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Drosera - Sundew", wateringDays: 3, emoji: "🪴"),
        PlantSpecies("Dudleya", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Dusty Miller", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Dwarf Umbrella Tree", wateringDays: 7, emoji: "🌳"),

        // E
        PlantSpecies("Echeveria", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Echeveria - Black Prince", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Echeveria - Lola", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Echeveria - Perle von Nurnberg", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Elephant Bush (Portulacaria)", wateringDays: 10, emoji: "🪴"),
        PlantSpecies("Elephant Ear", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("English Ivy", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Epiphyllum - Orchid Cactus", wateringDays: 10, emoji: "🌵"),
        PlantSpecies("Epipremnum - Pothos", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Episcia - Flame Violet", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Erica - Heather", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Eucalyptus", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Euonymus", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Euphorbia", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Euphorbia Tirucalli - Pencil Cactus", wateringDays: 14, emoji: "🪴"),

        // F
        PlantSpecies("Fan Palm", wateringDays: 7, emoji: "🌴"),
        PlantSpecies("Fatsia Japonica", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Fern - Asparagus", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Fern - Bird's Nest", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Fern - Blue Star", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Fern - Boston", wateringDays: 3, emoji: "🌿"),
        PlantSpecies("Fern - Button", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Fern - Holly", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Fern - Japanese Painted", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Fern - Kangaroo", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Fern - Maidenhair", wateringDays: 3, emoji: "🌿"),
        PlantSpecies("Fern - Rabbit's Foot", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Fern - Staghorn", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Fern - Sword", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Fern - Tree", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Ficus Audrey", wateringDays: 7, emoji: "🌳"),
        PlantSpecies("Ficus Benjamina", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Ficus Burgundy", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Ficus Elastica - Rubber Plant", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Ficus Lyrata - Fiddle Leaf Fig", wateringDays: 7, emoji: "🌳"),
        PlantSpecies("Ficus Microcarpa - Ginseng Fig", wateringDays: 7, emoji: "🌳"),
        PlantSpecies("Ficus Pumila - Creeping Fig", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Ficus Tineke", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Fig Tree (Indoor)", wateringDays: 7, emoji: "🌳"),
        PlantSpecies("Fittonia - Nerve Plant", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Flame Tree", wateringDays: 7, emoji: "🌳"),
        PlantSpecies("Flaming Katy (Kalanchoe)", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Forsythia", wateringDays: 7, emoji: "🌼"),
        PlantSpecies("Foxglove", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Frangipani", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Freesia", wateringDays: 7, emoji: "🌼"),
        PlantSpecies("Fuchsia", wateringDays: 5, emoji: "🌺"),

        // G
        PlantSpecies("Gardenia", wateringDays: 5, emoji: "🌼"),
        PlantSpecies("Gasteria", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Gazania", wateringDays: 7, emoji: "🌼"),
        PlantSpecies("Geranium", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Gerbera Daisy", wateringDays: 5, emoji: "🌼"),
        PlantSpecies("Ginger (Ornamental)", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Ginkgo (Indoor)", wateringDays: 7, emoji: "🌳"),
        PlantSpecies("Gladiolus", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Gloxinia", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Golden Pothos", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Graptopetalum", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Graptoveria", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Guzmania", wateringDays: 5, emoji: "🌺"),

        // H
        PlantSpecies("Haworthia", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Haworthia Cooperi", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Haworthia Fasciata - Zebra Plant", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Hedera - English Ivy", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Helenium - Sneezeweed", wateringDays: 5, emoji: "🌼"),
        PlantSpecies("Heliconia", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Heliotrope", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Hellebore", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Hens and Chicks (Sempervivum)", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Herbs - Basil", wateringDays: 3, emoji: "🌿"),
        PlantSpecies("Herbs - Bay Leaf", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Herbs - Chives", wateringDays: 3, emoji: "🌿"),
        PlantSpecies("Herbs - Cilantro", wateringDays: 3, emoji: "🌿"),
        PlantSpecies("Herbs - Dill", wateringDays: 3, emoji: "🌿"),
        PlantSpecies("Herbs - Lavender", wateringDays: 7, emoji: "💜"),
        PlantSpecies("Herbs - Lemongrass", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Herbs - Mint", wateringDays: 3, emoji: "🌿"),
        PlantSpecies("Herbs - Oregano", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Herbs - Parsley", wateringDays: 3, emoji: "🌿"),
        PlantSpecies("Herbs - Rosemary", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Herbs - Sage", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Herbs - Tarragon", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Herbs - Thyme", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Hibiscus", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Hippeastrum", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Holly", wateringDays: 7, emoji: "🌳"),
        PlantSpecies("Hollyhock", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Hosta", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Hoya - Wax Plant", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Hoya Carnosa", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Hoya Kerrii - Sweetheart Plant", wateringDays: 14, emoji: "💚"),
        PlantSpecies("Hoya Linearis", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Hoya Pubicalyx", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Hyacinth", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Hydrangea", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Hypoestes - Polka Dot Plant", wateringDays: 5, emoji: "🌿"),

        // I-J
        PlantSpecies("Ice Plant", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Impatiens", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Ipomoea - Morning Glory", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Iris", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Ixora", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Jade Plant", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Japanese Maple (Indoor)", wateringDays: 5, emoji: "🍁"),
        PlantSpecies("Jasmine", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Jasmine - Star", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Jatropha", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Juncus - Corkscrew Rush", wateringDays: 3, emoji: "🌿"),

        // K
        PlantSpecies("Kalanchoe", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Kalanchoe Tomentosa - Panda Plant", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Kangaroo Paw", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Kentia Palm", wateringDays: 7, emoji: "🌴"),
        PlantSpecies("King Protea", wateringDays: 7, emoji: "🌺"),

        // L
        PlantSpecies("Laceleaf (Anthurium)", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Lady Palm", wateringDays: 7, emoji: "🌴"),
        PlantSpecies("Lantana", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Larkspur", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Lavender", wateringDays: 7, emoji: "💜"),
        PlantSpecies("Lemon Tree", wateringDays: 7, emoji: "🍋"),
        PlantSpecies("Leopard Lily (Dieffenbachia)", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Lilac", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Lilium - Lily", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Lily of the Valley", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Lime Tree", wateringDays: 7, emoji: "🍋"),
        PlantSpecies("Lipstick Plant", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Lithops - Living Stones", wateringDays: 21, emoji: "🪴"),
        PlantSpecies("Lobelia", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Lollipop Plant (Pachystachys)", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Lotus", wateringDays: 3, emoji: "🌸"),
        PlantSpecies("Lupine", wateringDays: 5, emoji: "🌸"),

        // M
        PlantSpecies("Magnolia", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Majesty Palm", wateringDays: 5, emoji: "🌴"),
        PlantSpecies("Mammillaria Cactus", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Mandevilla", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Mango Tree (Indoor)", wateringDays: 7, emoji: "🥭"),
        PlantSpecies("Maranta - Prayer Plant", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Marigold", wateringDays: 5, emoji: "🌼"),
        PlantSpecies("Medinilla", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Meyer Lemon Tree", wateringDays: 7, emoji: "🍋"),
        PlantSpecies("Mimosa Pudica - Sensitive Plant", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Money Tree (Pachira)", wateringDays: 10, emoji: "🌳"),
        PlantSpecies("Monstera Adansonii", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Monstera Deliciosa", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Monstera Peru", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Monstera Thai Constellation", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Moses in the Cradle", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Musa - Banana Plant", wateringDays: 5, emoji: "🍌"),

        // N
        PlantSpecies("Narcissus - Daffodil", wateringDays: 5, emoji: "🌼"),
        PlantSpecies("Nasturtium", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Neanthe Bella Palm", wateringDays: 7, emoji: "🌴"),
        PlantSpecies("Neoregelia", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Nepenthes - Pitcher Plant", wateringDays: 3, emoji: "🪴"),
        PlantSpecies("Nephrolepis - Boston Fern", wateringDays: 3, emoji: "🌿"),
        PlantSpecies("Nerve Plant (Fittonia)", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("New Guinea Impatiens", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Norfolk Island Pine", wateringDays: 7, emoji: "🌲"),

        // O
        PlantSpecies("Oleander", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Olive Tree (Indoor)", wateringDays: 10, emoji: "🫒"),
        PlantSpecies("Oncidium - Dancing Lady Orchid", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Opuntia - Bunny Ears Cactus", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Opuntia - Prickly Pear", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Orange Tree (Indoor)", wateringDays: 7, emoji: "🍊"),
        PlantSpecies("Orchid - Cattleya", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Orchid - Cymbidium", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Orchid - Dendrobium", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Orchid - Lady Slipper", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Orchid - Miltonia", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Orchid - Oncidium", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Orchid - Phalaenopsis", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Orchid - Vanda", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Ornamental Grass", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Oxalis - Shamrock Plant", wateringDays: 5, emoji: "🍀"),

        // P
        PlantSpecies("Pachira - Money Tree", wateringDays: 10, emoji: "🌳"),
        PlantSpecies("Pachyphytum", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Panda Plant (Kalanchoe)", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Pansy", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Papyrus", wateringDays: 3, emoji: "🌿"),
        PlantSpecies("Parlor Palm", wateringDays: 7, emoji: "🌴"),
        PlantSpecies("Passionflower", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Peace Lily", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Peach Tree (Dwarf)", wateringDays: 7, emoji: "🍑"),
        PlantSpecies("Pelargonium - Scented Geranium", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Pentas", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Peony", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Peperomia", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Peperomia Hope", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Peperomia Obtusifolia", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Peperomia Rosso", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Peperomia Watermelon", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Periwinkle", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Persian Shield", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Petunia", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Philodendron", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Philodendron Birkin", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Philodendron Brasil", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Philodendron Gloriosum", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Philodendron Heartleaf", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Philodendron Micans", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Philodendron Pink Princess", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Philodendron Prince of Orange", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Philodendron Xanadu", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Phlox", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Phoenix Palm", wateringDays: 7, emoji: "🌴"),
        PlantSpecies("Pilea Peperomioides - Chinese Money Plant", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Pineapple Plant", wateringDays: 7, emoji: "🍍"),
        PlantSpecies("Pink Quill (Tillandsia)", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Pitcher Plant", wateringDays: 3, emoji: "🪴"),
        PlantSpecies("Platycerium - Staghorn Fern", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Plectranthus - Swedish Ivy", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Plumeria - Frangipani", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Poinsettia", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Polka Dot Plant", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Polyscias - Ming Aralia", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Pomegranate (Dwarf)", wateringDays: 7, emoji: "🌳"),
        PlantSpecies("Ponytail Palm", wateringDays: 14, emoji: "🌴"),
        PlantSpecies("Poppy", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Portulaca - Moss Rose", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Pothos - Golden", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Pothos - Marble Queen", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Pothos - Neon", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Pothos - Satin (Scindapsus)", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Prayer Plant", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Primrose", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Protea", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Purple Heart (Tradescantia)", wateringDays: 7, emoji: "🌿"),

        // R
        PlantSpecies("Rain Lily", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Ranunculus", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Raphidophora - Mini Monstera", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Rattlesnake Plant", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Rex Begonia", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Rhapis - Lady Palm", wateringDays: 7, emoji: "🌴"),
        PlantSpecies("Rhipsalis", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Rhododendron", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Rhoeo - Moses in the Cradle", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Rosa - Rose", wateringDays: 5, emoji: "🌹"),
        PlantSpecies("Rose - Miniature", wateringDays: 5, emoji: "🌹"),
        PlantSpecies("Rubber Plant", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Rudbeckia - Black-Eyed Susan", wateringDays: 5, emoji: "🌼"),

        // S
        PlantSpecies("Sago Palm", wateringDays: 10, emoji: "🌴"),
        PlantSpecies("Saintpaulia - African Violet", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Salvia", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Sansevieria - Snake Plant", wateringDays: 14, emoji: "🌱"),
        PlantSpecies("Sansevieria Cylindrica", wateringDays: 14, emoji: "🌱"),
        PlantSpecies("Sansevieria Moonshine", wateringDays: 14, emoji: "🌱"),
        PlantSpecies("Sansevieria Whale Fin", wateringDays: 14, emoji: "🌱"),
        PlantSpecies("Satin Pothos (Scindapsus)", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Schefflera", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Schlumbergera - Christmas Cactus", wateringDays: 10, emoji: "🌵"),
        PlantSpecies("Sedum", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Selaginella - Spikemoss", wateringDays: 3, emoji: "🌿"),
        PlantSpecies("Senecio - String of Bananas", wateringDays: 14, emoji: "🌿"),
        PlantSpecies("Senecio - String of Dolphins", wateringDays: 14, emoji: "🌿"),
        PlantSpecies("Senecio - String of Pearls", wateringDays: 14, emoji: "🌿"),
        PlantSpecies("Senecio - String of Turtles", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Shamrock Plant", wateringDays: 5, emoji: "🍀"),
        PlantSpecies("Shrimp Plant", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Silver Dollar Plant", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Snake Plant", wateringDays: 14, emoji: "🌱"),
        PlantSpecies("Snapdragon", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Snowdrop", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Spathiphyllum - Peace Lily", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Spider Plant", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Stapelia", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Stephanotis", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Stock (Matthiola)", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Streptocarpus - Cape Primrose", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Strelitzia - Bird of Paradise", wateringDays: 10, emoji: "🌺"),
        PlantSpecies("Stromanthe Triostar", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Succulent - Assorted", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Sunflower", wateringDays: 5, emoji: "🌻"),
        PlantSpecies("Sweet Pea", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Swiss Cheese Plant", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Syngonium - Arrowhead Plant", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Syngonium Pink", wateringDays: 7, emoji: "🌿"),

        // T
        PlantSpecies("Tansy", wateringDays: 7, emoji: "🌼"),
        PlantSpecies("Ti Plant", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Tiger Lily", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Tillandsia - Air Plant", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Tomato (Indoor)", wateringDays: 3, emoji: "🍅"),
        PlantSpecies("Torenia - Wishbone Flower", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Tradescantia", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Tradescantia Nanouk", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Tradescantia Zebrina", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Trillium", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Tropical Hibiscus", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Tulip", wateringDays: 5, emoji: "🌷"),
        PlantSpecies("Turmeric Plant", wateringDays: 5, emoji: "🌿"),

        // V
        PlantSpecies("Velvet Plant (Gynura)", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Venus Flytrap", wateringDays: 3, emoji: "🪴"),
        PlantSpecies("Verbena", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Vinca", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Viola", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Vriesea", wateringDays: 5, emoji: "🌺"),

        // W
        PlantSpecies("Wandering Jew", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Washingtonia Palm", wateringDays: 5, emoji: "🌴"),
        PlantSpecies("Wax Begonia", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Weeping Fig", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Wisteria", wateringDays: 5, emoji: "🌸"),

        // Y-Z
        PlantSpecies("Yucca", wateringDays: 14, emoji: "🌿"),
        PlantSpecies("Yucca Elephantipes", wateringDays: 14, emoji: "🌿"),
        PlantSpecies("Zamioculcas - ZZ Plant", wateringDays: 21, emoji: "🌿"),
        PlantSpecies("Zantedeschia - Calla Lily", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Zebra Plant (Aphelandra)", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Zinnia", wateringDays: 5, emoji: "🌸"),

        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        // Extended Database — 550+ additional species
        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

        // Additional A
        PlantSpecies("Abelia", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Abutilon Megapotamicum", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Acanthus - Bear's Breeches", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Acer Palmatum - Japanese Maple", wateringDays: 5, emoji: "🍁"),
        PlantSpecies("Achimenes - Hot Water Plant", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Aconitum - Monkshood", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Acorus - Sweet Flag", wateringDays: 3, emoji: "🌿"),
        PlantSpecies("Actaea - Baneberry", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Adenia", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Adromischus", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Aechmea - Silver Vase", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Aeonium Arboreum", wateringDays: 10, emoji: "🪴"),
        PlantSpecies("Aeonium Black Rose", wateringDays: 10, emoji: "🪴"),
        PlantSpecies("Aeonium Kiwi", wateringDays: 10, emoji: "🪴"),
        PlantSpecies("Aeonium Sunburst", wateringDays: 10, emoji: "🪴"),
        PlantSpecies("Agapanthus Blue", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Agastache - Hyssop", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Agave Americana", wateringDays: 21, emoji: "🪴"),
        PlantSpecies("Agave Blue Glow", wateringDays: 21, emoji: "🪴"),
        PlantSpecies("Agave Parryi", wateringDays: 21, emoji: "🪴"),
        PlantSpecies("Agave Victoria-Reginae", wateringDays: 21, emoji: "🪴"),
        PlantSpecies("Aglaonema Maria", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Aglaonema Silver Bay", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Aglaonema Silver Queen", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Akebia - Chocolate Vine", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Albuca Spiralis", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Allamanda", wateringDays: 5, emoji: "🌼"),
        PlantSpecies("Allium - Ornamental Onion", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Alocasia Black Velvet", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Alocasia Dragon Scale", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Alocasia Frydek", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Alocasia Maharani", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Alocasia Silver Dragon", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Aloe Aristata - Lace Aloe", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Aloe Brevifolia", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Aloe Juvenna - Tiger Tooth Aloe", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Aloe Polyphylla - Spiral Aloe", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Alstroemeria - Peruvian Lily", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Alyogyne - Blue Hibiscus", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Amorphophallus - Voodoo Lily", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Ampelopsis - Porcelain Berry", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Anigozanthos - Kangaroo Paw", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Anthurium Crystallinum", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Anthurium Magnificum", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Anthurium Veitchii - King Anthurium", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Anthurium Warocqueanum - Queen Anthurium", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Aquilegia - Columbine", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Arabis - Rock Cress", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Arachis - Peanut Plant", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Ardisia - Coral Berry", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Aristolochia - Dutchman's Pipe", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Armeria - Sea Thrift", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Arundina - Bamboo Orchid", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Asarina - Climbing Snapdragon", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Asclepias - Milkweed", wateringDays: 7, emoji: "🌸"),

        // Additional B
        PlantSpecies("Babiana - Baboon Flower", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Bambusa - Clumping Bamboo", wateringDays: 5, emoji: "🎋"),
        PlantSpecies("Banksia", wateringDays: 10, emoji: "🌺"),
        PlantSpecies("Baptisia - False Indigo", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Bauhinia - Orchid Tree", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Beautyberry (Callicarpa)", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Begonia Escargot", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Begonia Rieger", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Begonia Tuberous", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Bergenia - Elephant Ears", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Billbergia", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Blechnum - Hard Fern", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Bletilla - Hardy Orchid", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Bolbitis - Water Fern", wateringDays: 3, emoji: "🌿"),
        PlantSpecies("Borago - Borage", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Brachychiton - Bottle Tree", wateringDays: 14, emoji: "🌳"),
        PlantSpecies("Breynia - Snow Bush", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Brugmansia - Angel's Trumpet", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Brunfelsia Pauciflora", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Buddleia - Butterfly Bush", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Bulbine", wateringDays: 10, emoji: "🌼"),
        PlantSpecies("Buxus - Boxwood", wateringDays: 7, emoji: "🌳"),

        // Additional C
        PlantSpecies("Cactus - Acanthocereus", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Cactus - Apple (Cereus)", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Cactus - Blue Flame", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Cactus - Brain (Mammillaria)", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Cactus - Candelabra", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Cactus - Claret Cup", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Cactus - Coral", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Cactus - Eve's Needle", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Cactus - Fire Barrel", wateringDays: 21, emoji: "🌵"),
        PlantSpecies("Cactus - Ladyfinger", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Cactus - Mexican Fence Post", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Cactus - Night Blooming Cereus", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Cactus - Peruvian Apple", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Cactus - Teddy Bear Cholla", wateringDays: 21, emoji: "🌵"),
        PlantSpecies("Cactus - Turk's Cap", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Calathea Dottie", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Calathea Freddie", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Calathea Makoyana - Peacock Plant", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Calathea Musaica - Network Plant", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Calathea Ornata - Pin Stripe Plant", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Calathea Roseopicta", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Calathea Rufibarba - Furry Feather", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Calathea Setosa", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Calathea Triostar", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Calathea Zebrina", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Calceolaria - Slipper Flower", wateringDays: 5, emoji: "🌼"),
        PlantSpecies("Callisia Repens - Turtle Vine", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Callistemon - Bottlebrush", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Camellia Japonica", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Camellia Sinensis - Tea Plant", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Campsis - Trumpet Vine", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Canna - Indian Shot", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Capsicum - Ornamental Pepper", wateringDays: 5, emoji: "🌶"),
        PlantSpecies("Cardiocrinum - Giant Lily", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Carex - Sedge Grass", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Caryota - Fishtail Palm", wateringDays: 7, emoji: "🌴"),
        PlantSpecies("Cassia - Senna Plant", wateringDays: 7, emoji: "🌼"),
        PlantSpecies("Catharanthus - Madagascar Periwinkle", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Cattleya Orchid", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Centaurea - Cornflower", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Cephalocereus - Old Man Cactus", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Cerastium - Snow in Summer", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Chamaecyparis - False Cypress", wateringDays: 7, emoji: "🌲"),
        PlantSpecies("Chamaedorea Metallica", wateringDays: 7, emoji: "🌴"),
        PlantSpecies("Chamaerops - European Fan Palm", wateringDays: 7, emoji: "🌴"),
        PlantSpecies("Chelone - Turtlehead", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Chimonanthus - Wintersweet", wateringDays: 7, emoji: "🌼"),
        PlantSpecies("Chionodoxa - Glory of the Snow", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Chlorophytum Laxum", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Chrysalidocarpus - Areca", wateringDays: 5, emoji: "🌴"),
        PlantSpecies("Cineraria Maritima - Dusty Miller", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Cirsium - Ornamental Thistle", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Citrus - Calamondin Orange", wateringDays: 7, emoji: "🍊"),
        PlantSpecies("Citrus - Kumquat", wateringDays: 7, emoji: "🍊"),
        PlantSpecies("Clarkia", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Cleome - Spider Flower", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Clethra - Summersweet", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Clianthus - Parrot's Beak", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Cobaea - Cup and Saucer Vine", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Cocos Nucifera - Coconut Palm", wateringDays: 7, emoji: "🌴"),
        PlantSpecies("Colocasia - Taro", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Commelina - Dayflower", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Convallaria - Lily of the Valley", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Coprosma - Mirror Plant", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Cornus - Dogwood", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Cortaderia - Pampas Grass", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Cotyledon", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Crassula Muscosa - Watch Chain", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Crassula Ovata - Gollum Jade", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Crassula Perforata - String of Buttons", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Crinum Lily", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Crocosmia - Montbretia", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Cryptanthus - Earth Star", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Cryptomeria - Japanese Cedar", wateringDays: 7, emoji: "🌲"),
        PlantSpecies("Curcuma - Hidden Ginger", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Cyanotis - Teddy Bear Vine", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Cycas - Sago Palm", wateringDays: 10, emoji: "🌴"),
        PlantSpecies("Cymbopogon - Lemongrass", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Cypella", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Cyperus - Umbrella Palm", wateringDays: 3, emoji: "🌿"),
        PlantSpecies("Cyrtomium - Holly Fern", wateringDays: 5, emoji: "🌿"),

        // Additional D
        PlantSpecies("Dahlia Cactus", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Dahlia Pompon", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Darlingtonia - Cobra Lily", wateringDays: 3, emoji: "🪴"),
        PlantSpecies("Delosperma - Ice Plant", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Dendrobium Nobile", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Dendrobium Phalaenopsis", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Dianella - Flax Lily", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Dichorisandra - Blue Ginger", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Dicksonia - Tree Fern", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Dictamnus - Gas Plant", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Dietes - Fortnight Lily", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Dipladenia", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Disporum - Fairy Bells", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Dizygotheca - False Aralia", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Dorotheanthus - Livingstone Daisy", wateringDays: 10, emoji: "🌼"),
        PlantSpecies("Doryanthes - Spear Lily", wateringDays: 10, emoji: "🌺"),
        PlantSpecies("Dracaena Compacta", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Dracaena Fragrans - Corn Plant", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Dracaena Marginata - Dragon Tree", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Dracaena Reflexa - Song of India", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Drimys - Winter's Bark", wateringDays: 7, emoji: "🌳"),
        PlantSpecies("Duranta - Sky Flower", wateringDays: 7, emoji: "🌸"),

        // Additional E
        PlantSpecies("Echeveria Agavoides", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Echeveria Chroma", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Echeveria Elegans", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Echeveria Imbricata", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Echeveria Laui", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Echeveria Lilacina", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Echeveria Pulidonis", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Echeveria Setosa", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Echinocereus - Hedgehog Cactus", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Echinops - Globe Thistle", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Edgeworthia - Paper Bush", wateringDays: 5, emoji: "🌼"),
        PlantSpecies("Eichhornia - Water Hyacinth", wateringDays: 3, emoji: "🌸"),
        PlantSpecies("Elaeagnus - Silverberry", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Elymus - Blue Lyme Grass", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Enkianthus", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Epipremnum Aureum - Devil's Ivy", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Epipremnum Cebu Blue", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Epipremnum Pinnatum", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Eranthis - Winter Aconite", wateringDays: 5, emoji: "🌼"),
        PlantSpecies("Eremurus - Foxtail Lily", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Erigeron - Fleabane", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Eryngium - Sea Holly", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Erythrina - Coral Tree", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Eucomis - Pineapple Lily", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Eugenia - Brush Cherry", wateringDays: 7, emoji: "🌳"),
        PlantSpecies("Euphorbia Ammak", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Euphorbia Ingens", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Euphorbia Lactea - Dragon Bones", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Euphorbia Obesa - Baseball Plant", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Euphorbia Trigona - African Milk Tree", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Eustoma - Lisianthus", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Exacum - Persian Violet", wateringDays: 5, emoji: "🌸"),

        // Additional F
        PlantSpecies("Farfugium - Leopard Plant", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Felicia - Blue Daisy", wateringDays: 5, emoji: "🌼"),
        PlantSpecies("Fenestraria - Baby Toes", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Fern - Australian Tree Fern", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Fern - Brake Fern (Pteris)", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Fern - Cinnamon Fern", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Fern - Crocodile Fern", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Fern - Delta Maidenhair", wateringDays: 3, emoji: "🌿"),
        PlantSpecies("Fern - Foxtail Fern", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Fern - Heart Fern", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Fern - Korean Rock Fern", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Fern - Lemon Button Fern", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Fern - Leather Fern", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Fern - Ostrich Fern", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Fern - Royal Fern", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Fern - Silver Lady Fern", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Ficus Altissima", wateringDays: 7, emoji: "🌳"),
        PlantSpecies("Ficus Binnendijkii - Alii Fig", wateringDays: 7, emoji: "🌳"),
        PlantSpecies("Ficus Carica - Edible Fig", wateringDays: 7, emoji: "🌳"),
        PlantSpecies("Ficus Deltoidea - Mistletoe Fig", wateringDays: 7, emoji: "🌳"),
        PlantSpecies("Ficus Religiosa - Sacred Fig", wateringDays: 7, emoji: "🌳"),
        PlantSpecies("Ficus Ruby", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Ficus Shivereana", wateringDays: 7, emoji: "🌳"),
        PlantSpecies("Filipendula - Meadowsweet", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Firmiana - Chinese Parasol Tree", wateringDays: 7, emoji: "🌳"),

        // Additional G
        PlantSpecies("Gaillardia - Blanket Flower", wateringDays: 7, emoji: "🌼"),
        PlantSpecies("Galanthus - Snowdrop", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Galium - Sweet Woodruff", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Gaura - Beeblossom", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Gelsemium - Carolina Jessamine", wateringDays: 7, emoji: "🌼"),
        PlantSpecies("Gentiana - Gentian", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Gesneria", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Gladiolus - Sword Lily", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Globba - Dancing Lady Ginger", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Gloriosa - Flame Lily", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Goeppertia", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Gomphrena - Globe Amaranth", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Gordonia", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Graptopetalum Paraguayense - Ghost Plant", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Grevillea - Spider Flower", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Grewia - Lavender Star", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Gunnera - Giant Rhubarb", wateringDays: 5, emoji: "🌿"),

        // Additional H
        PlantSpecies("Haemanthus - Blood Lily", wateringDays: 10, emoji: "🌺"),
        PlantSpecies("Hakea", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Hamamelis - Witch Hazel", wateringDays: 7, emoji: "🌼"),
        PlantSpecies("Hardenbergia - Happy Wanderer", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Haworthia Attenuata", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Haworthia Cymbiformis", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Haworthia Limifolia", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Haworthia Retusa", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Haworthia Truncata", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Hedychium - Ginger Lily", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Helianthemum - Rock Rose", wateringDays: 7, emoji: "🌼"),
        PlantSpecies("Helianthus - Sunflower", wateringDays: 5, emoji: "🌻"),
        PlantSpecies("Helichrysum - Strawflower", wateringDays: 7, emoji: "🌼"),
        PlantSpecies("Helleborus Niger - Christmas Rose", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Herbs - Chamomile", wateringDays: 5, emoji: "🌼"),
        PlantSpecies("Herbs - Chervil", wateringDays: 3, emoji: "🌿"),
        PlantSpecies("Herbs - Curry Leaf", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Herbs - Epazote", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Herbs - Fennel", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Herbs - Lemon Balm", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Herbs - Lemon Verbena", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Herbs - Marjoram", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Herbs - Sorrel", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Herbs - Stevia", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Herbs - Summer Savory", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Herbs - Winter Savory", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Hesperaloe - Red Yucca", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Heuchera - Coral Bells", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Hibiscus Rosa-sinensis", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Hibiscus Syriacus - Rose of Sharon", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Hippeastrum Papilio", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Homalomena", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Hosta Blue Angel", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Hosta Sum and Substance", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Hovea", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Howea Forsteriana - Kentia Palm", wateringDays: 7, emoji: "🌴"),
        PlantSpecies("Hoya Australis", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Hoya Compacta - Hindu Rope", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Hoya Curtisii", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Hoya Mathilde", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Hoya Multiflora", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Hoya Obovata", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Hoya Retusa", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Hoya Shepherdii - String Bean Hoya", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Hoya Wayetii", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Humulus - Hops", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Hymenocallis - Spider Lily", wateringDays: 7, emoji: "🌸"),

        // Additional I-J
        PlantSpecies("Iberis - Candytuft", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Ilex - Holly", wateringDays: 7, emoji: "🌳"),
        PlantSpecies("Illicium - Star Anise", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Incarvillea - Hardy Gloxinia", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Iochroma - Mini Brugmansia", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Iresine - Bloodleaf", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Iris Germanica - Bearded Iris", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Iris Reticulata - Dwarf Iris", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Isotoma - Blue Star Creeper", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Itea - Sweetspire", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Jacaranda", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Jacobinia - Brazilian Plume", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Jasminum Polyanthum - Pink Jasmine", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Jasminum Sambac - Arabian Jasmine", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Jatropha Podagrica - Buddha Belly", wateringDays: 10, emoji: "🌺"),
        PlantSpecies("Jovellana", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Juglans - Walnut Tree", wateringDays: 7, emoji: "🌳"),
        PlantSpecies("Juniperus - Juniper", wateringDays: 10, emoji: "🌲"),
        PlantSpecies("Justicia - Shrimp Plant", wateringDays: 5, emoji: "🌺"),

        // Additional K
        PlantSpecies("Kaempferia - Peacock Ginger", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Kalanchoe Beharensis - Felt Plant", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Kalanchoe Blossfeldiana", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Kalanchoe Daigremontiana - Mother of Thousands", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Kalanchoe Delagoensis - Chandelier Plant", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Kalanchoe Fedtschenkoi", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Kalanchoe Luciae - Paddle Plant", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Kalanchoe Thyrsiflora - Flapjack", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Kerria - Japanese Rose", wateringDays: 7, emoji: "🌼"),
        PlantSpecies("Kirengeshoma - Yellow Waxbells", wateringDays: 5, emoji: "🌼"),
        PlantSpecies("Kniphofia - Red Hot Poker", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Koelreuteria - Golden Rain Tree", wateringDays: 7, emoji: "🌳"),
        PlantSpecies("Kolkwitzia - Beauty Bush", wateringDays: 7, emoji: "🌸"),

        // Additional L
        PlantSpecies("Lachenalia - Cape Cowslip", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Lagerstroemia - Crepe Myrtle", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Lamium - Dead Nettle", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Lapageria - Chilean Bellflower", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Lathyrus - Sweet Pea", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Laurus Nobilis - Bay Tree", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Lavandula Stoechas - French Lavender", wateringDays: 7, emoji: "💜"),
        PlantSpecies("Lavatera - Tree Mallow", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Ledebouria - Silver Squill", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Leonotis - Lion's Tail", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Leptospermum - Tea Tree", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Leucadendron", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Leucanthemum - Shasta Daisy", wateringDays: 5, emoji: "🌼"),
        PlantSpecies("Leucojum - Snowflake", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Leucospermum - Pincushion Protea", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Lewisia", wateringDays: 10, emoji: "🌸"),
        PlantSpecies("Liatris - Blazing Star", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Ligularia", wateringDays: 5, emoji: "🌼"),
        PlantSpecies("Ligustrum - Privet", wateringDays: 7, emoji: "🌳"),
        PlantSpecies("Linum - Flax", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Livistona - Fan Palm", wateringDays: 7, emoji: "🌴"),
        PlantSpecies("Lonicera - Honeysuckle", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Lophophora - Peyote", wateringDays: 21, emoji: "🌵"),
        PlantSpecies("Ludisia Discolor - Jewel Orchid", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Luculia", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Lunaria - Money Plant", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Lycaste Orchid", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Lycoris - Spider Lily", wateringDays: 10, emoji: "🌺"),
        PlantSpecies("Lysimachia - Loosestrife", wateringDays: 5, emoji: "🌼"),

        // Additional M
        PlantSpecies("Macleaya - Plume Poppy", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Macodes Petola - Jewel Orchid", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Mahonia", wateringDays: 7, emoji: "🌼"),
        PlantSpecies("Malus - Crabapple", wateringDays: 7, emoji: "🌳"),
        PlantSpecies("Malvaviscus - Turk's Cap", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Manettia - Candy Corn Plant", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Maranta Leuconeura Kerchoveana", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Matthiola - Stock Flower", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Mazus - Creeping Mazus", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Meconopsis - Himalayan Blue Poppy", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Melaleuca - Paperbark Tree", wateringDays: 7, emoji: "🌳"),
        PlantSpecies("Melia - Chinaberry", wateringDays: 7, emoji: "🌳"),
        PlantSpecies("Melianthus - Honey Bush", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Mertensia - Virginia Bluebells", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Metrosideros - Pohutukawa", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Michelia - Banana Shrub", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Microsorium - Kangaroo Fern", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Miltoniopsis Orchid", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Monstera Obliqua", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Monstera Pinnatipartita", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Monstera Siltepecana", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Monstera Standleyana", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Moraea - Butterfly Iris", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Muehlenbeckia - Wire Vine", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Murraya - Orange Jasmine", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Muscari - Grape Hyacinth", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Myosotis - Forget-Me-Not", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Myrtus - Myrtle", wateringDays: 7, emoji: "🌿"),

        // Additional N
        PlantSpecies("Nandina - Heavenly Bamboo", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Nelumbo - Sacred Lotus", wateringDays: 3, emoji: "🌸"),
        PlantSpecies("Nemesia", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Nepeta - Catmint", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Nephrolepis Exaltata - Fluffy Ruffle Fern", wateringDays: 3, emoji: "🌿"),
        PlantSpecies("Nerine - Guernsey Lily", wateringDays: 10, emoji: "🌸"),
        PlantSpecies("Nicotiana - Flowering Tobacco", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Nidularium", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Nigella - Love in a Mist", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Nolina - Beargrass", wateringDays: 14, emoji: "🌿"),
        PlantSpecies("Nymphaea - Water Lily", wateringDays: 3, emoji: "🌸"),

        // Additional O
        PlantSpecies("Ochna - Mickey Mouse Plant", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Oenothera - Evening Primrose", wateringDays: 7, emoji: "🌼"),
        PlantSpecies("Olea Europaea - Olive Tree", wateringDays: 10, emoji: "🫒"),
        PlantSpecies("Oncidium Sharry Baby", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Ophiopogon - Mondo Grass", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Opuntia Microdasys - Angel Wings", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Opuntia Monacantha", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Orchid - Brassavola", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Orchid - Brassia - Spider Orchid", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Orchid - Coelogyne", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Orchid - Epidendrum", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Orchid - Laelia", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Orchid - Ludisia", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Orchid - Masdevallia", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Orchid - Maxillaria", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Orchid - Paphiopedilum", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Orchid - Zygopetalum", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Ornithogalum - Star of Bethlehem", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Orostachys", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Osmanthus - Sweet Olive", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Osteospermum - African Daisy", wateringDays: 7, emoji: "🌼"),

        // Additional P
        PlantSpecies("Pachypodium - Madagascar Palm", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Pachyveria", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Paeonia - Peony", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Palm - Alexander Palm", wateringDays: 7, emoji: "🌴"),
        PlantSpecies("Palm - Bismarck Palm", wateringDays: 7, emoji: "🌴"),
        PlantSpecies("Palm - Bottle Palm", wateringDays: 7, emoji: "🌴"),
        PlantSpecies("Palm - Canary Island Date Palm", wateringDays: 7, emoji: "🌴"),
        PlantSpecies("Palm - Cat Palm", wateringDays: 5, emoji: "🌴"),
        PlantSpecies("Palm - Chinese Fan Palm", wateringDays: 7, emoji: "🌴"),
        PlantSpecies("Palm - Coconut Palm", wateringDays: 7, emoji: "🌴"),
        PlantSpecies("Palm - Date Palm", wateringDays: 7, emoji: "🌴"),
        PlantSpecies("Palm - Foxtail Palm", wateringDays: 7, emoji: "🌴"),
        PlantSpecies("Palm - King Palm", wateringDays: 7, emoji: "🌴"),
        PlantSpecies("Palm - MacArthur Palm", wateringDays: 7, emoji: "🌴"),
        PlantSpecies("Palm - Pygmy Date Palm", wateringDays: 5, emoji: "🌴"),
        PlantSpecies("Palm - Queen Palm", wateringDays: 7, emoji: "🌴"),
        PlantSpecies("Palm - Royal Palm", wateringDays: 7, emoji: "🌴"),
        PlantSpecies("Palm - Spindle Palm", wateringDays: 7, emoji: "🌴"),
        PlantSpecies("Palm - Triangle Palm", wateringDays: 7, emoji: "🌴"),
        PlantSpecies("Palm - Windmill Palm", wateringDays: 7, emoji: "🌴"),
        PlantSpecies("Pandanus - Screw Pine", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Papaver - Poppy", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Paphiopedilum - Venus Slipper", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Passiflora Caerulea - Blue Passionflower", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Paulownia - Princess Tree", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Pedilanthus - Devil's Backbone", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Pelargonium Graveolens - Rose Geranium", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Pellaea - Button Fern", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Pennisetum - Fountain Grass", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Penstemon - Beardtongue", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Peperomia Argyreia - Watermelon", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Peperomia Caperata - Emerald Ripple", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Peperomia Polybotrya - Raindrop", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Peperomia Prostrata - String of Turtles", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Peperomia Rotundifolia", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Perovskia - Russian Sage", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Persicaria - Knotweed", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Petrea - Purple Wreath", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Phalaenopsis - Moth Orchid", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Philodendron Billietiae", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Philodendron Bipennifolium", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Philodendron Erubescens", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Philodendron Florida Ghost", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Philodendron Hastatum - Silver Sword", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Philodendron Hope - Selloum", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Philodendron Lemon Lime", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Philodendron Mamei", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Philodendron Melanochrysum", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Philodendron Moonlight", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Philodendron Painted Lady", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Philodendron Paraiso Verde", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Philodendron Pedatum", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Philodendron Plowmanii", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Philodendron Red Emerald", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Philodendron Ring of Fire", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Philodendron Rojo Congo", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Philodendron Squamiferum", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Philodendron Tortum", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Philodendron Verrucosum", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Philodendron White Knight", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Philodendron White Princess", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Phlebodium - Blue Star Fern", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Photinia - Red Robin", wateringDays: 7, emoji: "🌳"),
        PlantSpecies("Phyllostachys - Running Bamboo", wateringDays: 5, emoji: "🎋"),
        PlantSpecies("Physalis - Chinese Lantern", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Pieris - Andromeda", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Pilea Cadierei - Aluminum Plant", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Pilea Depressa - Baby Tears", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Pilea Involucrata - Friendship Plant", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Pilea Mollis - Moon Valley", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Pinguicula - Butterwort", wateringDays: 3, emoji: "🪴"),
        PlantSpecies("Pinus - Dwarf Pine", wateringDays: 7, emoji: "🌲"),
        PlantSpecies("Pistacia - Pistachio Tree", wateringDays: 10, emoji: "🌳"),
        PlantSpecies("Pittosporum", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Platanus - Sycamore", wateringDays: 7, emoji: "🌳"),
        PlantSpecies("Plumbago", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Podocarpus - Buddhist Pine", wateringDays: 7, emoji: "🌲"),
        PlantSpecies("Podranea - Pink Trumpet Vine", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Pogostemon - Patchouli", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Polemonium - Jacob's Ladder", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Polygonatum - Solomon's Seal", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Polygonum - Knotweed", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Polypodium - Polypody Fern", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Pothos - Cebu Blue", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Pothos - Global Green", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Pothos - Hawaiian", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Pothos - Jade", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Pothos - Manjula", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Pothos - N'Joy", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Pothos - Pearls and Jade", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Pothos - Snow Queen", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Primula Auricula", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Prostanthera - Mint Bush", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Prunus - Ornamental Cherry", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Pseuderanthemum", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Pteris - Table Fern", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Pulmonaria - Lungwort", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Punica - Pomegranate", wateringDays: 7, emoji: "🌳"),
        PlantSpecies("Pyracantha - Firethorn", wateringDays: 7, emoji: "🌳"),

        // Additional R
        PlantSpecies("Radermachera - China Doll", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Ranunculus Asiaticus - Persian Buttercup", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Raphiolepis - Indian Hawthorn", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Raven ZZ Plant", wateringDays: 21, emoji: "🌿"),
        PlantSpecies("Rebutia - Crown Cactus", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Rhaphidophora Decursiva", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Rhaphidophora Tetrasperma", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Rhapis Excelsa - Lady Palm", wateringDays: 7, emoji: "🌴"),
        PlantSpecies("Rhodiola - Stonecrop", wateringDays: 10, emoji: "🪴"),
        PlantSpecies("Rhus - Sumac", wateringDays: 7, emoji: "🌳"),
        PlantSpecies("Ribes - Flowering Currant", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Ricinus - Castor Bean Plant", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Rivina - Rouge Plant", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Rodgersia", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Romneya - Matilija Poppy", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Rosmarinus - Rosemary", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Rubus - Ornamental Bramble", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Ruellia - Mexican Petunia", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Russelia - Firecracker Plant", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Ruta - Rue", wateringDays: 7, emoji: "🌿"),

        // Additional S
        PlantSpecies("Saintpaulia Ionantha", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Salix - Pussy Willow", wateringDays: 5, emoji: "🌳"),
        PlantSpecies("Salvinia - Water Fern", wateringDays: 3, emoji: "🌿"),
        PlantSpecies("Sambucus - Elderberry", wateringDays: 7, emoji: "🌳"),
        PlantSpecies("Sanchezia", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Sansevieria Bantel's Sensation", wateringDays: 14, emoji: "🌱"),
        PlantSpecies("Sansevieria Black Coral", wateringDays: 14, emoji: "🌱"),
        PlantSpecies("Sansevieria Fernwood", wateringDays: 14, emoji: "🌱"),
        PlantSpecies("Sansevieria Francisii", wateringDays: 14, emoji: "🌱"),
        PlantSpecies("Sansevieria Masoniana - Whale Fin", wateringDays: 14, emoji: "🌱"),
        PlantSpecies("Sansevieria Starfish", wateringDays: 14, emoji: "🌱"),
        PlantSpecies("Sansevieria Zeylanica", wateringDays: 14, emoji: "🌱"),
        PlantSpecies("Santolina - Lavender Cotton", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Sarracenia - Pitcher Plant (American)", wateringDays: 3, emoji: "🪴"),
        PlantSpecies("Scabiosa - Pincushion Flower", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Scaevola - Fan Flower", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Schefflera Amate", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Schefflera Arboricola - Dwarf Umbrella", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Schismatoglottis", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Sciadopitys - Japanese Umbrella Pine", wateringDays: 7, emoji: "🌲"),
        PlantSpecies("Scilla - Squill", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Scindapsus Pictus - Silver Pothos", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Scindapsus Treubii - Moonlight", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Sedum Adolphii - Golden Sedum", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Sedum Burrito - Baby Burro's Tail", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Sedum Rubrotinctum - Jelly Bean", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Sempervivum - Houseleek", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Senecio Barbertonicus - Succulent Bush", wateringDays: 14, emoji: "🌿"),
        PlantSpecies("Senecio Haworthii - Cocoon Plant", wateringDays: 14, emoji: "🌿"),
        PlantSpecies("Senecio Rowleyanus - String of Pearls", wateringDays: 14, emoji: "🌿"),
        PlantSpecies("Serissa - Tree of a Thousand Stars", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Sidalcea - Prairie Mallow", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Sinningia - Florist's Gloxinia", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Skimmia", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Solanum - Nightshade", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Solanum Jasminoides - Potato Vine", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Soleirolia - Baby's Tears", wateringDays: 3, emoji: "🌿"),
        PlantSpecies("Solidago - Goldenrod", wateringDays: 7, emoji: "🌼"),
        PlantSpecies("Sophora - Kowhai", wateringDays: 7, emoji: "🌼"),
        PlantSpecies("Sparaxis - Harlequin Flower", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Spathoglottis - Ground Orchid", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Spiraea", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Stachys - Lamb's Ear", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Stanhopea Orchid", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Stenocactus", wateringDays: 14, emoji: "🌵"),
        PlantSpecies("Stenotaphrum - St. Augustine Grass", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Sternbergia - Winter Daffodil", wateringDays: 7, emoji: "🌼"),
        PlantSpecies("Stokesia - Stokes' Aster", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Strelitzia Nicolai - White Bird of Paradise", wateringDays: 10, emoji: "🌺"),
        PlantSpecies("Streptocarpella", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Strobilanthes - Persian Shield", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Succulent - Aeonium Mix", wateringDays: 10, emoji: "🪴"),
        PlantSpecies("Succulent - Crassula Mix", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Succulent - Echeveria Mix", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Succulent - Haworthia Mix", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Succulent - Sedum Mix", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Syngonium Albo", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Syngonium Berry Allusion", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Syngonium Mango", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Syngonium Neon Robusta", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Syngonium White Butterfly", wateringDays: 7, emoji: "🌿"),

        // Additional T
        PlantSpecies("Tacca - Bat Flower", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Tagetes - Marigold", wateringDays: 5, emoji: "🌼"),
        PlantSpecies("Tamarindus - Tamarind", wateringDays: 7, emoji: "🌳"),
        PlantSpecies("Taxus - Yew", wateringDays: 7, emoji: "🌲"),
        PlantSpecies("Tecoma - Yellow Bells", wateringDays: 7, emoji: "🌼"),
        PlantSpecies("Tecomaria - Cape Honeysuckle", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Tetranema - Mexican Foxglove", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Tetrastigma - Chestnut Vine", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Thalictrum - Meadow Rue", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Thuja - Arborvitae", wateringDays: 7, emoji: "🌲"),
        PlantSpecies("Thunbergia - Black-Eyed Susan Vine", wateringDays: 5, emoji: "🌼"),
        PlantSpecies("Thymus - Creeping Thyme", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Tibouchina - Princess Flower", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Tigridia - Tiger Flower", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Tillandsia Bulbosa", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Tillandsia Caput-Medusae", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Tillandsia Ionantha", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Tillandsia Tectorum", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Tillandsia Usneoides - Spanish Moss", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Tillandsia Xerographica", wateringDays: 10, emoji: "🌿"),
        PlantSpecies("Tolmiea - Piggyback Plant", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Trachelospermum - Star Jasmine", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Trachycarpus - Windmill Palm", wateringDays: 7, emoji: "🌴"),
        PlantSpecies("Tradescantia Fluminensis", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Tradescantia Pallida - Purple Heart", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Tradescantia Sillamontana - White Velvet", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Tradescantia Spathacea - Moses in Cradle", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Tricyrtis - Toad Lily", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Tropaeolum - Nasturtium", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Tulbaghia - Society Garlic", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Tulipa - Species Tulip", wateringDays: 5, emoji: "🌷"),

        // Additional U-V
        PlantSpecies("Ugni - Chilean Guava", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Uncarina", wateringDays: 14, emoji: "🪴"),
        PlantSpecies("Vaccinium - Blueberry", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Valeriana - Valerian", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Vanda Orchid", wateringDays: 5, emoji: "🌺"),
        PlantSpecies("Vanilla - Vanilla Orchid", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Veratrum - False Hellebore", wateringDays: 5, emoji: "🌿"),
        PlantSpecies("Verbascum - Mullein", wateringDays: 7, emoji: "🌼"),
        PlantSpecies("Veronica - Speedwell", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Viburnum", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Vinca Major - Periwinkle", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Viola Odorata - Sweet Violet", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Vitex - Chaste Tree", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Vitis - Grape Vine", wateringDays: 7, emoji: "🍇"),
        PlantSpecies("Vriesea Splendens - Flaming Sword", wateringDays: 5, emoji: "🌺"),

        // Additional W
        PlantSpecies("Wahlenbergia - Rock Bell", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Watsonia", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Weigela", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Westringia - Coastal Rosemary", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Wollemia - Wollemi Pine", wateringDays: 7, emoji: "🌲"),

        // Additional X-Y-Z
        PlantSpecies("Xanthorrhoea - Grass Tree", wateringDays: 14, emoji: "🌿"),
        PlantSpecies("Xanthosoma - Elephant Ear", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Xerosicyos - Silver Dollar Vine", wateringDays: 14, emoji: "🌿"),
        PlantSpecies("Yucca Aloifolia - Spanish Bayonet", wateringDays: 14, emoji: "🌿"),
        PlantSpecies("Yucca Filamentosa", wateringDays: 14, emoji: "🌿"),
        PlantSpecies("Yucca Gloriosa", wateringDays: 14, emoji: "🌿"),
        PlantSpecies("Yucca Rostrata", wateringDays: 14, emoji: "🌿"),
        PlantSpecies("Zamia - Cardboard Palm", wateringDays: 14, emoji: "🌿"),
        PlantSpecies("Zamioculcas Zamiifolia Raven", wateringDays: 21, emoji: "🌿"),
        PlantSpecies("Zantedeschia Aethiopica - White Calla", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Zanthoxylum - Szechuan Pepper", wateringDays: 7, emoji: "🌿"),
        PlantSpecies("Zauschneria - California Fuchsia", wateringDays: 7, emoji: "🌺"),
        PlantSpecies("Zelkova - Japanese Elm", wateringDays: 7, emoji: "🌳"),
        PlantSpecies("Zenobia", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Zephyranthes - Rain Lily", wateringDays: 5, emoji: "🌸"),
        PlantSpecies("Zigadenus", wateringDays: 7, emoji: "🌸"),
        PlantSpecies("Zygopetalum Orchid", wateringDays: 7, emoji: "🌺"),

        PlantSpecies("Custom", wateringDays: 7, emoji: "🌱"),
    ]

    /// Search the plant species database by name (case-insensitive, partial match)
    static func search(query: String) -> [PlantSpecies] {
        guard !query.trimmingCharacters(in: .whitespaces).isEmpty else {
            return database
        }
        let lowercaseQuery = query.lowercased()
        return database.filter { $0.name.lowercased().contains(lowercaseQuery) }
    }

    /// Get a specific plant species by exact name match
    static func species(named name: String) -> PlantSpecies? {
        database.first { $0.name == name }
    }
}
